# Generated by Django 4.0.6 on 2024-05-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apresentacao', models.TextField()),
                ('objetivos', models.TextField()),
                ('competencias', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('ects', models.IntegerField()),
                ('curricular', models.CharField(max_length=20)),
                ('area_cientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.areacientifica')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('conceitos_usados', models.TextField()),
                ('tecnologias_usadas', models.TextField()),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('video', models.URLField()),
                ('github', models.URLField()),
                ('disciplina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='LinguagemProgramacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('projetos', models.ManyToManyField(to='curso.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('disciplinas', models.ManyToManyField(to='curso.disciplina')),
            ],
        ),
    ]
