# Generated by Django 4.0.6 on 2024-03-18 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='numero_Musicas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='bandas.banda'),
        ),
    ]
