# Generated by Django 4.0.6 on 2024-04-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_album_numero_musicas_alter_album_banda'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='ano_lancamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banda',
            name='ano_criacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='banda',
            name='numero_Mebros',
            field=models.IntegerField(default=0),
        ),
    ]
