# Generated by Django 4.0.6 on 2024-04-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_album_ano_lancamento_banda_ano_criacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banda',
            old_name='numero_Mebros',
            new_name='numero_membros',
        ),
    ]
