# Generated by Django 4.0.6 on 2024-04-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_rename_numero_mebros_banda_numero_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='foto_Banda',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
