# Generated by Django 4.0.6 on 2024-04-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_alter_banda_foto_banda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='foto_Banda',
            field=models.ImageField(default='0', upload_to=None),
        ),
    ]
