# Generated by Django 4.0.6 on 2024-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_alter_banda_foto_banda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='capa',
            field=models.ImageField(default='0', upload_to=None),
        ),
    ]
