# Generated by Django 4.0.6 on 2024-04-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_alter_album_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
