# Generated by Django 4.0.6 on 2024-04-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_musica_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musica',
            name='duracao',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='musica',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musica',
            name='tipo',
            field=models.CharField(max_length=200),
        ),
    ]
