# Generated by Django 4.0.6 on 2024-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_alter_album_nome_alter_banda_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='numero_Musicas',
        ),
        migrations.AddField(
            model_name='album',
            name='numero_musicas',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
