# Generated by Django 4.0.6 on 2024-04-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0010_remove_album_numero_musicas_album_numero_musicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to='bandas.banda'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
