# Generated by Django 4.0.6 on 2024-03-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_alter_post_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.CharField(max_length=100000),
        ),
    ]
